{% set name = "RoboMeshCat" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/petrikvladimir/RoboMeshCat/archive/v{{ version }}.tar.gz
  sha256: cac3b880cca089511442756fe6fc3a10a61f3674869bccae1c79d765c998cdbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pinocchio
    - meshcat-python
    - trimesh
    - imageio
    - imageio-ffmpeg

test:
  imports:
    - robomeshcat
#  commands:
 #   - pip check
#  requires:
 #   - pip

about:
  home: https://github.com/petrikvladimir/RoboMeshCat
  summary: Set of utilities for visualizing robots in web-based visualizer MeshCat.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - petrikvladimir
