{% set name = "RoboMeshCat" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/petrikvladimir/RoboMeshCat/archive/v{{ version }}.tar.gz
  sha256: ff1ff276a724e6527c9416e8db7ce242bba098682d6a481db7f684372515ae8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pinocchio
    - meshcat-python
    - trimesh
    - imageio
    - imageio-ffmpeg

test:
  imports:
    - robomeshcat
#  commands:
 #   - pip check
#  requires:
 #   - pip

about:
  home: https://github.com/petrikvladimir/RoboMeshCat
  summary: Set of utilities for visualizing robots in web-based visualizer MeshCat.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - petrikvladimir
